name: monitoria_app
description: Aplicativo para o preenchimento da folha ponto da UDESC. Criado por Vinícius Takeo

publish_to: "none"

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.8.1
  google_sign_in: ^4.5.5
  firebase_auth: ^0.18.1+2
  flutter_auth_buttons: ^0.10.0
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+3
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.2
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon/mascarar.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
